server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
#management:
#  tracing:
#    sampling:
#      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false